#!/bin/bash

green='\033[0;32m'
yellow='\033[0;33m'
end='\033[0m'
brightblue='\033[1;34m'

echo -e "${green}Adding linted files to commit${end}"

files=$(cat $PWD/files_for_commit.txt)



if [[ $files == "" ]]
then
    echo -e "${brightblue}No more files to commit${end}"
    exit 0
fi

for file in $files
do
    echo -e "${yellow}Adding $file${end}"
    git add $file
done

echo "NO PRECOMMIT" > $PWD/files_for_commit.txt

git commit --amend --no-edit

echo -e "${green}All is and done, ready for a push... :)${end}"

exit 0

