#!/bin/bash

# If you encounter any issues trying to commit
# Do not hesitate to ping me @asynchroza so I can help you :)

green='\033[0;32m'
yellow='\033[0;33m'
end='\033[0m'
brightblue='\033[1;34m'

echo -e "${green}Adding linted files to commit${end}"

files=$(cat $PWD/files_for_commit.txt)



if [[ $files == "" ]]
then
    echo -e "${brightblue}No more files to commit${end}"
    exit 0
fi

for file in $files
do
    echo -e "${yellow}Adding $file${end}"
    git add $file
done

echo "NO PRECOMMIT" > $PWD/files_for_commit.txt

git commit --amend --no-edit

echo -e "\n\n\n"
echo -e "${green}All is set and done, ready for a push... :)${end}"
echo -e "${brightblue}If you encounter any issues, ping ${yellow}@asynchroza${end}"

exit 0

