version: '3'

services:

# API
  server:
    build: 
      context: ./packages/api
      target: final 
    container_name: api
    depends_on: 
      - client
    expose: 
      - 8000
    ports:
      - 8000:8000
    command: /api
    volumes:
      - ./data/certs:/app/certs
    networks:
      - front-back

# WEB
  client:
    build: ./packages/web
    container_name: web
    expose:
      - 443
    ports:
      - 80:80
      - 443:443
    command: nginx -g 'daemon off';
    volumes: 
      - ./data/certs:/etc/nginx/certs
    networks:
      - front-back

networks:
  front-back:
    driver: bridge
