version: '3'

services:

# API
  server:
    build: ./packages/api
    expose: 
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    command: /api

# WEB
  client:
    build: ./packages/web
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    links:
      - server
    command: nginx -g 'daemon off';
