services:
  py-api:
    image: ghcr.io/aubgthehub/monolith:${GIT_COMMIT_HASH:-latest}
    ports:
      - "8080:8080"
    environment:
      ENV: /run/secrets/env
      ADDRESS: /run/secrets/address
      DOMAIN: /run/secrets/domain
      PORT: 8080
      DATABASE_URL: /run/secrets/db-url
      SECRET_KEY: /run/secrets/secret-key
      SECRET_AUTH_TOKEN: /run/secrets/secret-auth-key
    secrets:
      - env
      - address
      - domain
      - db-url
      - secret-key
      - secret-auth-key
    deploy:
      update_config:
        order: start-first
    volumes:
      - /services/py-api/shared:/app/shared
      - /etc/letsencrypt:/etc/letsencrypt

secrets:
  env:
    external: true
  address:
    external: true
  domain:
    external: true
  db-url:
    external: true
  secret-key:
    external: true
  secret-auth-key:
    external: true
