version: '3'

services:

# API
  server:
    build: ./packages/api
    container_name: api
    expose: 
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    command: /api

# WEB
  client:
    build: ./packages/web
    container_name: web
    expose:
      - ${REACT_APP_PORT}
    ports:
      - 80:80
      - 443:443
    links:
      - "server"
    command: nginx -g 'daemon off';
    volumes:
      - ./data/certs:/etc/nginx/certs
