services:
  py-api:
    image: ghcr.io/aubgthehub/monolith:${GIT_COMMIT_HASH:-latest}
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      # The values of the env variables are the paths where the decrypted secret is mounted into the container in an
      # in-memory filesystem.
      # IMPORTANT: Services should implement an app-level logic to read the decrypted values from those mounted files,
      # otherwise the values of these env variable will stay the mounted paths!
      # https://docs.docker.com/engine/swarm/secrets/#how-docker-manages-secrets
      ENV: /run/secrets/env
      ADDRESS: /run/secrets/address
      DOMAIN: /run/secrets/domain
      PORT: 8080
      DATABASE_URL: /run/secrets/db-url
      SECRET_KEY: /run/secrets/secret-key
      SECRET_AUTH_TOKEN: /run/secrets/secret-auth-key
    secrets:
      - env
      - address
      - domain
      - db-url
      - secret-key
      - secret-auth-key
    deploy:
      update_config:
        order: start-first
    volumes:
      - /services/py-api/shared:/app/shared
      - /etc/letsencrypt:/etc/letsencrypt

secrets:
  # These docker secrets have already been set on the PROD and DEV VMs, that's why we use external: true.
  # To set a new secret key-value pair you may use: `prinf "toniMsecret" | docker secret create toni -`
  env:
    external: true
  address:
    external: true
  domain:
    external: true
  db-url:
    external: true
  secret-key:
    external: true
  secret-auth-key:
    external: true
