from typing import Final

from fastapi.middleware.cors import CORSMiddleware
from fastapi import FastAPI


class EnableCorsMiddleware:
    def __init__(self, app: FastAPI):
        # Warning is generated by PyCharm: https://github.com/fastapi/fastapi/discussions/10968#discussioncomment-11004400
        app.add_middleware(
            CORSMiddleware,
            allow_origins=self._construct_origins(),
            allow_methods=["*"],
            allow_headers=["*"],
            allow_credentials=True,
        )

    @staticmethod
    def _construct_origins() -> list[str]:
        allowed_localhost_ports: Final = [80, 3000, 3001]
        allowed_localhost_domains: Final = ["localhost", "127.0.0.1"]
        allowed_localhost_protocols: Final = ["http", "https"]
        origins = [
            f"{protocol}://{domain}:{port}"
            for protocol in allowed_localhost_protocols
            for domain in allowed_localhost_domains
            for port in allowed_localhost_ports
        ]

        # there's no need for ports here since the api is behind a proxy
        allowed_public_domains = [
            "https://dev.thehub-aubg.com",
            "https://thehub-aubg.com",
        ]

        origins.extend(allowed_public_domains)

        return origins
