from fastapi.middleware.cors import CORSMiddleware
from fastapi import FastAPI


class EnableCorsMiddleware:
    def __init__(self, app: FastAPI):
        # Warning is generated by PyCharm: https://github.com/fastapi/fastapi/discussions/10968#discussioncomment-11004400
        app.add_middleware(
            CORSMiddleware,
            allow_origins=["*"],  # Allow all origins
            allow_methods=["*"],  # Allow all HTTP methods
            allow_headers=["*"],  # Allow all headers
            allow_credentials=True,  # Allow credentials
        )
