import { HackathonSponsorProps } from './HackathonSponsors';

export const Sponsors: HackathonSponsorProps[] = [
    {
        name: 'Base Line',
        rank: 'Platinum',
        logoSrc: 'https://hubarskibucket.s3.eu-central-1.amazonaws.com/baselinefixed.png',
        websiteLink: 'https://google.com',
    },
    {
        name: 'Betahaus Sofia',
        rank: 'Gold',
        logoSrc: 'https://hubarskibucket.s3.eu-central-1.amazonaws.com/betahaus-sofia-logo.png',
        websiteLink: 'https://google.com',
    },
    {
        name: 'Bianor',
        rank: 'Silver',
        logoSrc: 'https://hubarskibucket.s3.eu-central-1.amazonaws.com/Bianor-logo.png',
        websiteLink: 'https://google.com',
    },
    {
        name: 'Bosh',
        rank: 'Platinum',
        logoSrc: 'https://hubarskibucket.s3.eu-central-1.amazonaws.com/boshnew.svg',
        websiteLink: 'https://google.com',
    },
    {
        name: 'Carbon',
        rank: 'Gold',
        logoSrc: 'https://hubarskibucket.s3.eu-central-1.amazonaws.com/carbon.webp',
        websiteLink: 'https://google.com',
    },
    {
        name: 'Centio',
        rank: 'Silver',
        logoSrc: 'https://hubarskibucket.s3.eu-central-1.amazonaws.com/centio.png',
        websiteLink: 'https://google.com',
    },
    {
        name: 'Codexio',
        rank: 'Platinum',
        logoSrc: 'https://hubarskibucket.s3.eu-central-1.amazonaws.com/codexio-logo.png',
        websiteLink: 'https://google.com',
    },
    {
        name: 'Commerzbank',
        rank: 'Gold',
        logoSrc: 'https://hubarskibucket.s3.eu-central-1.amazonaws.com/Commerzbank-logo.png',
        websiteLink: 'https://google.com',
    },
    {
        name: 'Dev.bg',
        rank: 'Silver',
        logoSrc: 'https://hubarskibucket.s3.eu-central-1.amazonaws.com/devBgLogo.png',
        websiteLink: 'https://google.com',
    },
    {
        name: 'DevStyleR',
        rank: 'Platinum',
        logoSrc: 'https://hubarskibucket.s3.eu-central-1.amazonaws.com/DevStyleR-logo.png',
        websiteLink: 'https://google.com',
    },
    {
        name: 'eAcademia',
        rank: 'Gold',
        logoSrc: 'https://hubarskibucket.s3.eu-central-1.amazonaws.com/eAcademia.png',
        websiteLink: 'https://google.com',
    },
    {
        name: 'Eviden',
        rank: 'Silver',
        logoSrc: 'https://hubarskibucket.s3.eu-central-1.amazonaws.com/eviden.webp',
        websiteLink: 'https://google.com',
    },
    {
        name: 'Gameloft',
        rank: 'Platinum',
        logoSrc: 'https://hubarskibucket.s3.eu-central-1.amazonaws.com/Gameloft-logo.png',
        websiteLink: 'https://google.com',
    },
    {
        name: 'HackSoft',
        rank: 'Gold',
        logoSrc: 'https://hubarskibucket.s3.eu-central-1.amazonaws.com/ITCE-logo.png',
        websiteLink: 'https://google.com',
    },
    {
        name: 'M2M',
        rank: 'Silver',
        logoSrc: 'https://hubarskibucket.s3.eu-central-1.amazonaws.com/m2m.png',
        websiteLink: 'https://google.com',
    },
    {
        name: 'MentorMate',
        rank: 'Platinum',
        logoSrc: 'https://hubarskibucket.s3.eu-central-1.amazonaws.com/Tuk-Tam-logo.png',
        websiteLink: 'https://google.com',
    },
    {
        name: 'Musala Soft',
        rank: 'Gold',
        logoSrc: 'https://hubarskibucket.s3.eu-central-1.amazonaws.com/yettel.svg',
        websiteLink: 'https://google.com',
    },
    {
        name: 'Resolute',
        rank: 'Silver',
        logoSrc: 'https://hubarskibucket.s3.eu-central-1.amazonaws.com/resolute-logo.png',
        websiteLink: 'https://google.com',
    },
    {
        name: 'MentorMate',
        rank: 'Custom',
        logoSrc: 'https://hubarskibucket.s3.eu-central-1.amazonaws.com/Tuk-Tam-logo.png',
        websiteLink: 'https://google.com',
    },
    {
        name: 'Musala Soft',
        rank: 'Custom',
        logoSrc: 'https://hubarskibucket.s3.eu-central-1.amazonaws.com/yettel.svg',
        websiteLink: 'https://google.com',
    },
    {
        name: 'Resolute',
        rank: 'Custom',
        logoSrc: 'https://hubarskibucket.s3.eu-central-1.amazonaws.com/resolute-logo.png',
        websiteLink: 'https://google.com',
    },
    {
        name: 'MentorMate',
        rank: 'Bronze',
        logoSrc: 'https://hubarskibucket.s3.eu-central-1.amazonaws.com/Tuk-Tam-logo.png',
        websiteLink: 'https://google.com',
    },
    {
        name: 'Musala Soft',
        rank: 'Bronze',
        logoSrc: 'https://hubarskibucket.s3.eu-central-1.amazonaws.com/yettel.svg',
        websiteLink: 'https://google.com',
    },
    {
        name: 'Resolute',
        rank: 'Bronze',
        logoSrc: 'https://hubarskibucket.s3.eu-central-1.amazonaws.com/resolute-logo.png',
        websiteLink: 'https://google.com',
    },
];
