[tool.poetry]
name = "py-api"
version = "0.1.0"
description = ""
authors = ["Michael Bozhilov <michaelbozhilov@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.101.1"
uvicorn = {extras = ["standard"], version = "^0.23.2"}
requests = "^2.31.0"
boto3 = "^1.28.33"
python-multipart = "^0.0.6"
pymongo = "^4.5.0"
python-dotenv = "^1.0.0"
psutil = "^5.9.5"

[tool.poetry.scripts]
start = "py_api.main:start"
rename_collection = "py_api.scripts.rename_collection:rename_collection"

[tool.poetry.group.dev.dependencies]
setuptools = "^68.1.2"
pre-commit = "^3.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
