name: Build Frontend
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths: ['packages/web/**']
jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the frontend
        run: cd ./packages/web && docker build .
