name: Build Python Backend
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths: ['packages/py-api/**']

env:
  CON_STR: '${{ secrets.CON_STR }}'
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Python Backend
        run: cd ./packages/py-api && docker build . --build-arg CON_STR=$CON_STR
