name: Initiate Dev Environmnet Deployment

on:
    push: #Add back master branch after testing
env:
    DEV_VM_IP: '${{secrets.DEV_VM_IP}}'
    DEV_VM_PSWD: '${{secrets.DEV_VM_PSWD}}'
    DISCORD_WH: '${{secrets.DEPLOYMENT_CHANNEL_WEBHOOK}}'
jobs:
    deploy:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10"]

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                python3 -m pip install --upgrade pip
                pip3 install paramiko

            - name: Extract branch name
              id: extract_branch_name
              run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

            - name: Start deployment
              run: |
                ./start_deployment.py --ip ${DEV_VM_IP} --pswd ${DEV_VM_PSWD} --discordwh ${DISCORD_WH} --branch ${{ steps.extract_branch_name.outputs.branch }}
