name: Notify Discord
on:
  pull_request:
    types: [opened]
jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: "```css\nPR-{{ EVENT_PAYLOAD.pull_request.number }}: '{{ EVENT_PAYLOAD.pull_request.title }}' has been opened by {{ EVENT_PAYLOAD.pull_request.user.login }}\n``` \n [Go To PR:]({{ EVENT_PAYLOAD.pull_request.html_url }})"