name: Deployment Pipeline

on:
  push:
    branches:
      - 'main'
      - 'production'
    paths:
      # Back-end Paths that will trigger re-deployment
      - 'services/py-api/src/**'
      - 'services/py-api/Dockerfile'
      - 'services/py-api/**/*.lock'
      - 'services/py-api/**/*.toml'

      # Front-end paths that will trigger re-deployment
      - 'services/web/src/**'
      - 'services/web/Dockerfile'
      - 'services/web/package-lock.json'
      - 'services/web/package.json'
      - 'services/web/nginx.*.conf'
      - 'services/web/*.config.*'
      - 'services/web/tsconfig.*'
      - 'services/web/*.html'

permissions:
  packages: write

jobs:

  build-and-push-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }} # https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication
          password: ${{ secrets.GITHUB_TOKEN }}

      # We run the job conditionally so that we only build the python API when changes are made to it
      - name: Build and push Docker image for the python API
        uses: docker/build-push-action@v6
        with:
          context: ./services/py-api/
          push: true
          tags: |
            ghcr.io/aubgthehub/monolith-backend:latest
            ghcr.io/aubgthehub/monolith-backend:${{ github.sha }}

      - name: Set environment variables based on branch to pass them to the WEB builder
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "VITE_ENV=DEV" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "VITE_ENV=PROD" >> $GITHUB_ENV
          else
            echo "VITE_ENV=DEV" >> $GITHUB_ENV
          fi

      # We run the job conditionally so that we only build the Web Client when changes are made to it
      - name: Build and push Docker image for the WEB client
        uses: docker/build-push-action@v6
        with:
          context: ./services/web/
          push: true
          tags: |
            ghcr.io/aubgthehub/monolith-web:latest
            ghcr.io/aubgthehub/monolith-web:${{ github.sha }}
          # We pass the build arguments for the frontend
          # https://docs.docker.com/reference/cli/docker/buildx/build/#build-arg
          build-args: |
            VITE_ENV=${{ env.VITE_ENV }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-images
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Here we create the ./envfile that the GitHub Actions runner is going to use for the next step - Deployment! (see below)
      # Since we don't have the repository cloned in the VPS, we have no information of the git commit that the image that we want to
      # pull and run is coming from. For this reason, we pass the commit hash to the next step, which is explained below.
      - name: Install mktemp
        run: sudo apt-get update && sudo apt-get install -y mktemp
      - name: create env file
        run: |
          echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile
          # Set DOMAIN based on the branch being pushed
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "DOMAIN=dev.thehub-aubg.com" >> ./envfile
          elif [[ "${{ github.ref_name }}" == "master" ]]; then
            echo "DOMAIN=thehub-aubg.com" >> ./envfile
          else
            echo "DOMAIN=dev.thehub-aubg.com" >> ./envfile
          fi
      # Below we use a GitHub Actions template that is created for the purpose of deploying utilizing both Docker Stack and Docker Context.
      # You can find the source repo here: https://github.com/cssnr/stack-deploy-action
      # name - This will be used as a tag to the Docker Stack the we are going to deploy to Docker Swarm installed on the VPS
      # file - The docker stack config file, it similar to a docker-compose file, but also quite different
      # host - The domain of the target deployment VPS
      # user - The user created on the VPS that has docker privilleges (Can only run docker command)
      # ssh_key - The private ssh key that is used to authenticate into the VPS user that we are utilizing for deployment (Should be stored in the repository secrets)
      # and finally we pass the ./envfile that was created by the step above in the working directory of the GitHub Actions runner.
      # This ./envfile is sourced by the runner and then used by docker stack when doing docker stack deploy to the VPS to pull the latest project image.
      # Links for further reading
      # Read more about Docker Stack: https://docs.docker.com/reference/cli/docker/stack/deploy/
      # Read more about Docker Swarm: https://forums.docker.com/t/docker-swarm-series-8th-publishing-modes/136972
      # Read more about Docker Context:  https://docs.docker.com/engine/manage-resources/contexts/
      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: monolith
          file: docker-swarm-stack.yml
          host: ${{ github.ref_name == 'main' && 'dev.thehub-aubg.com' || 'thehub-aubg.com' }}
          user: deploy
          ssh_key: ${{ github.ref_name == 'main' && secrets.DEV_DEPLOY_SSH_PRIVATE_KEY || secrets.PROD_DEPLOY_SSH_PRIVATE_KEY }}
          env_file: ./envfile
