name: Build Frontend
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the frontend
        run: cd ./packages/web && docker build .
