name: Build web and test internal library

on:
    pull_request:
        types: [assigned, opened, synchronize, reopened]
        paths:
            - 'services/web/**'

jobs:
    build_and_test_frontend:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Debug repository structure
              run: ls -R

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '23'

            - name: Cache npm dependencies
              uses: actions/cache@v4
              with:
                  path: services/web/node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('services/web/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install dependencies
              working-directory: services/web
              run: npm install

            - name: Build the frontend
              working-directory: services/web
              run: npm run build

            - name: Run frontend tests
              working-directory: services/web
              run: npm test

            - name: Upload coverage reports
              uses: actions/upload-artifact@v4
              with:
                  name: coverage-reports
                  path: ./services/web/test-report.html
